name: Scheduled automerge.

on:
  # Keeps failing, try enabling again in future.
  # status:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  automerge:
    if: startsWith( github.repository, 'Homebrew/' )
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./.github/actions/automerge
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
