name: Automerge

on:
  push:
    branches:
      - debug-automerge
  schedule:
    - cron: '0 * * * *'
  workflow_run:
    workflows:
      - CI
    types:
      - completed
  pull_request_review:
    types:
      - submitted
  pull_request_target:
    types:
      - unlabeled
      - ready_for_review
  workflow_dispatch:
    inputs:
      pull-request:
        description: Pull Request Number
        required: false

jobs:
  automerge:
    if: >
      startsWith(github.repository, 'Homebrew/') &&
      (
        (
          github.event.review.state == 'approved' &&
          github.event.pull_request.base.repo.full_name == github.event.pull_request.head.repo.full_name
        ) || github.event_name != 'pull_request_review'
      )
    runs-on: ubuntu-latest
    steps:
      - uses: reitermarkus/automerge@29daf0958167ca86edcc536a3f0cb5cae056c11f
        with:
          token: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
          merge-method: squash
          squash-title: true
          do-not-merge-labels: 'do not merge,awaiting maintainer feedback,awaiting user reply'
          pull-request: ${{ github.event.inputs.pull-request }}
          dry-run: ${{ github.ref == 'refs/heads/debug-automerge' }}
