name: Rebase Pull Request

on:
  repository_dispatch:
    types: [rebase-command]

permissions:
  contents: read

jobs:
  rebase_pull_request:
    name: Rebase Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Rebase Pull Request
        uses: peter-evans/rebase@56c359b35ff7ba8426d0fdb842958b35b1db8277
        id: rebase
        with:
          token: ${{ secrets.HOMEBREW_CASK_REBASE_TOKEN }}
          head: ${{ github.event.client_payload.pull_request.head.label }}

      - name: Add üëç Reaction
        if: always() && steps.rebase.outputs.rebased-count == 1
        uses: peter-evans/create-or-update-comment@23ff15729ef2fc348714a3bb66d2f655ca9066f2
        with:
          token: ${{ secrets.HOMEBREW_GITHUB_PUBLIC_REPO_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reactions: '+1'

      - name: Add üëé Reaction
        if: always() && steps.rebase.outputs.rebased-count != 1
        uses: peter-evans/create-or-update-comment@23ff15729ef2fc348714a3bb66d2f655ca9066f2
        with:
          token: ${{ secrets.HOMEBREW_GITHUB_PUBLIC_REPO_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reactions: '-1'
